### ISSUE TITLE
Negotiated Rates and Freight

### ISSUE THREAD

**Issue by DavidShochet** [alexeybusygin/ShippingRates#19]
Здравствуйте, Алексей!

I am trying to use your solution for getting negotiated rates:

            rateManager.AddProvider(new UPSProvider(upsLicenseNumber, upsUsername, upsPassword) { UseNegotiatedRates = true, UseProduction = false });

But the rate I get back is the same, whether UseNegotiatedRates is true or false. I guess, ShipperNumber should be required, but if so, where can I provide it? Or anything else I may be missing?

Also, I see your package deals with UPS packages, but how about freight?

Thank you very much!

**Comment by DavidShochet** [comment]
OK, I looked at the code and figured out how to supply ShipperNumber. So now I need to know if the package allows getting freight rate rather than package. Please advise.

**Comment by alexeybusygin** [comment]
Hello David!

I've added some documentation on [negotiated rates ](https://github.com/alexeybusygin/ShippingRates/wiki/Negotiated-Rates), hope it will help. The ShippingRates package works only with package rates because we use UPS Rating Package XML API. Freight rates are available at UPS SOAP API for the Rating Package Web Service and other specific APIs like UPS SOAP API for the Rating Ground Freight Web Service. At this moment we are not planning to implement this.
