### ISSUE TITLE
Support for UK shipping

### ISSUE THREAD

**Issue by jentrinanes** [alexeybusygin/ShippingRates#27]
Seems the code only works for US or Canada shipments. Please include domestic shipments in UK.

**Comment by alexeybusygin** [comment]
As far as I can see DHL and UPS works fine. For FedEx, you will need an account "enabled for domestic shipping in the United Kingdom" (according to the FedEx site). If you have one then could you please tell me what Errors and InternalErrors do you get?

**Comment by alexeybusygin** [comment]
Could you please post the list of error messages you receive (from both Errors and InternalErrors fields)?

**Comment by jentrinanes** [comment]
I get 2 errors:
 - There are no valid services available
 - The origin state/province code has been changed

I can ignore the 2nd error because I only pass UK post code and GB country code. But it doesn't return rates.

**Comment by alexeybusygin** [comment]
The problem seems to be not with the ShippingRates. The error "no valid services available" is coming directly from FedEx API. Could you please login to the FedEx site and try to get rates with their online Rate & Ship calculator? If you get a message like the one below then you may need to contact FedEx Support:

![image](https://user-images.githubusercontent.com/3892338/132982512-b21fd259-c8cc-4d40-acf1-e664dbfa8b8e.png)
